# Generated by Django 5.1.3 on 2024-12-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_original', models.CharField(max_length=255)),
                ('titulo_portugues', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('genero', models.CharField(max_length=255)),
                ('diretor', models.CharField(max_length=255)),
                ('elenco', models.CharField(max_length=255)),
                ('duracao', models.IntegerField()),
                ('lancamento', models.DateField()),
                ('classificacao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Individuo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('contato', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
