name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-and-test:
    name: Validate and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13.0

      - name: Install Django dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django tests
        run: python manage.py test

      - name: Auto-generate requirements.txt
        run: |
          pip freeze > requirements.txt
        continue-on-error: true

      # Step 6: Set up Node.js fr React
      #- name: Set up Node.js
      #  uses: actions/setup-node@v3
      #  with:
      #    node-version: 22.10.0

      #- name: Install React dependencies
      #  working-directory: frontend
      #  run: npm install

      #- name: Run React tests
      #  working-directory: frontend
      #  run: npm test -- --watchAll=false

      #- name: Run ESLint
      #  working-directory: frontend
      #  run: npx eslint . --ext .js,.jsx,.ts,.tsx